[package]
name = "game_of_life"
version = "0.1.0"
edition = "2021"

[dependencies]
grid = "0.15.0"
rand = "0.8.5"

[dependencies.raylib]
version = "5.0.2"
features = ["wayland", "custom_frame_control"]
